<template>
    <main-layout>
        <h3 class="text-2xl font-extrabold mb-5">Dashboard</h3>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam posuere turpis quis magna pulvinar scelerisque. Donec bibendum ante et arcu semper, in auctor nulla sagittis. Aliquam elementum quis erat ut pharetra. Etiam quis aliquam tellus. Mauris est arcu, semper in vestibulum non, feugiat a lectus. Sed suscipit facilisis placerat. Maecenas euismod, lacus eu rhoncus bibendum, libero ligula pulvinar lacus, non lacinia orci purus ac quam. Praesent quis orci a lacus pellentesque finibus vitae eu lorem. Etiam vestibulum pellentesque ipsum, eget faucibus velit dictum ac. Curabitur nec purus tristique ante elementum dictum. Donec et bibendum purus.

Proin id massa vulputate eros rutrum egestas sit amet ut metus. Vivamus venenatis lacinia nisi eu pellentesque. Vivamus eleifend egestas augue a hendrerit. Donec ultrices elit id odio auctor viverra. Maecenas ut arcu lacus. Praesent congue turpis quis erat rhoncus interdum. Proin ipsum odio, rutrum non faucibus vitae, efficitur in purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi volutpat nibh non mauris tincidunt, vel pretium mauris ultricies. Proin faucibus feugiat metus id congue. Aliquam erat volutpat. Aenean et ipsum lobortis, ullamcorper nisi at, congue tortor. Morbi a justo maximus, elementum eros maximus, luctus libero. In consectetur tellus neque, et consectetur mi ullamcorper at. Etiam nec fermentum tortor.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer iaculis eget leo ut lobortis. Quisque hendrerit quam eget metus fringilla, a commodo sem aliquam. Suspendisse euismod, turpis id aliquam congue, enim diam cursus purus, tempor ullamcorper orci augue a leo. Phasellus dui leo, lobortis ut fringilla in, consectetur sed magna. Maecenas massa enim, eleifend vel imperdiet et, bibendum eget risus. Vivamus vel tortor turpis. Vestibulum mattis ex malesuada, semper erat non, vehicula diam. Quisque interdum congue odio et tempus. Proin quis neque cursus, elementum arcu vel, porta massa. Nunc sed sagittis leo. Nam id volutpat mauris, non auctor ex. Mauris interdum ornare vulputate.

Suspendisse potenti. Duis tellus arcu, egestas vitae orci vitae, congue fermentum massa. Pellentesque faucibus viverra volutpat. Nulla nec dolor sed dolor blandit vestibulum. Mauris sed odio tincidunt, condimentum orci id, mattis velit. Duis mattis nulla sed justo congue, non blandit dui ultrices. Nam commodo massa ipsum, eu hendrerit neque tincidunt vitae. Donec ut finibus mi. Aliquam varius luctus magna ac maximus. Donec sed suscipit nisi, ut condimentum erat. Vestibulum ac tempor augue. Maecenas sollicitudin nulla nec est pulvinar eleifend. Mauris pretium venenatis lorem, quis ullamcorper enim commodo sit amet.

Proin in diam in turpis sagittis viverra. Vestibulum eu pulvinar mi. Nam id nisi non mi sagittis fringilla. Donec aliquam, lacus quis lobortis gravida, dolor odio tincidunt sem, a pellentesque neque orci ut sapien. Nullam nec sapien nec tortor imperdiet tempus. Quisque orci velit, auctor at nisl sed, fermentum mollis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam accumsan vulputate ante, a aliquet nulla congue et. Vivamus accumsan augue est, ut luctus quam porta ac. Nunc eleifend urna pellentesque, porttitor nisi quis, ultrices arcu. Morbi auctor, ante id convallis auctor, risus neque tincidunt magna, eu venenatis felis tortor eu erat. Pellentesque arcu felis, dapibus a mauris vel, aliquam ultricies elit. Morbi enim leo, vehicula sit amet pellentesque vulputate, dictum nec dolor. Nunc lobortis tincidunt nulla sed congue.

Aliquam mattis volutpat neque et rhoncus. Praesent dapibus ligula lectus, nec imperdiet magna varius eget. Ut tempus, nunc nec tristique elementum, nibh ligula maximus dui, eget ullamcorper odio ex vel nisi. Nulla varius eleifend urna eget vulputate. Maecenas vitae luctus justo, ut maximus nibh. Proin dictum dolor nec sagittis aliquam. Maecenas sollicitudin vitae erat eu mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In commodo sodales sodales. Etiam aliquet turpis elit, sit amet viverra ligula semper a. Morbi nec diam diam. Integer ex lacus, venenatis ac tortor et, ultrices feugiat ligula. Aliquam aliquet gravida fringilla.

Vestibulum augue lorem, interdum eu ante sed, tristique feugiat augue. Phasellus aliquet purus sit amet maximus semper. Maecenas consequat rutrum dolor, et iaculis est pretium ac. Suspendisse sed dapibus enim. Aenean blandit tellus et dolor gravida egestas. Duis euismod sit amet lectus eu pharetra. Mauris facilisis arcu et lorem imperdiet egestas. Cras convallis interdum lectus, eu bibendum eros mollis vitae. Integer malesuada ante ut lacinia tristique. Fusce dapibus erat purus, nec lacinia sapien rutrum sit amet.

Aenean nec fermentum ipsum. Integer non enim hendrerit, aliquet diam viverra, egestas tortor. Pellentesque rhoncus tortor et nulla vestibulum, at tempor est gravida. Praesent dapibus massa est, ac consequat justo semper ac. Fusce mattis aliquam ligula ac vulputate. Fusce elementum pretium neque. Suspendisse a ex sit amet mi porttitor tristique eu in purus. Phasellus ligula ipsum, auctor et metus id, dapibus congue diam. Nunc accumsan dapibus risus quis consectetur. Donec sit amet arcu fermentum, pellentesque risus vel, bibendum ante.

Vestibulum ac vestibulum eros, id varius diam. Sed id porta lorem. Maecenas rutrum ornare risus et mattis. Curabitur a mauris nulla. Suspendisse blandit augue a leo efficitur hendrerit. Fusce faucibus ante velit, nec ullamcorper orci auctor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis accumsan dapibus est eget vulputate. Cras sagittis libero luctus felis interdum, ornare tincidunt metus efficitur.

Vivamus quis mauris eu velit dapibus iaculis sed sit amet eros. Aenean consequat nibh eu erat mattis vehicula. Nunc tristique vel diam nec pretium. Etiam commodo maximus nibh in aliquam. Sed tellus velit, condimentum ut est et, efficitur pellentesque neque. Aenean posuere arcu non facilisis tempus. Suspendisse potenti. Aenean lacinia, dolor a dignissim vulputate, tortor dolor congue mi, sed egestas enim lacus quis justo. Nullam tempus sit amet purus vel bibendum. Phasellus eget rhoncus lorem, nec tristique magna. Donec elit justo, molestie sit amet vehicula in, semper accumsan est. Donec ultrices ante sed blandit iaculis. Phasellus tincidunt arcu eget sem tristique finibus. Proin nec interdum leo, id ornare felis. Nulla sed lacus in massa imperdiet ullamcorper sed et arcu.
    </main-layout>
</template>

<script setup>
import MainLayout from '@/Layouts/MainLayout.vue';
</script>